[package]
name = "peano-natural"
version = "0.2.1"
authors = ["M Farkas-Dyck <strake888@gmail.com>"]
description = "Type-level Peano naturals"
license = "MIT OR Apache-2.0"
repository = "https://github.com/strake/libreal.rs"

[lib]
name = "peano"
